import tkinter as tk
from tkinter import filedialog, messagebox
#from tkinter import ttk
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2Tk
from matplotlib.figure import Figure
import picnik as pnk
import numpy as np
import chardet
import os
import sys
import subprocess
import shutil
import pandas as pd
import re
import ttkbootstrap as ttk
#from ttkbootstrap.constants import *
from ttkbootstrap.dialogs import Messagebox

class Aplicacion(ttk.Window):
    """
    Graphical interface for managing and visualizing isoconversion calculations.
    This class manages a Tkinter window that allows interaction with the
    Picnik calculation module. It is responsible for capturing user input data,
    invoking processing methods,
    rendering useful graphs for analysis, and
    exporting data and graphs generated by Picnik.
    """
    
    def __init__(self):
        """
        inicia la ventana principal
        """
        
        """
        Starts the main window
        """
        self.tema="darkly"
        super().__init__(themename=self.tema)
        self.title("Picnik desktop edition")
        self.geometry("1280x720")
        self.minsize(820,600)

        """
        interface variables
        """
       
        self.fase_actual = tk.IntVar(value=1)
        
        
        """
        picnik support variables
        """
        
        self.one_step=[]
        self.numero_de_archivos=0
        self.fig=None
        self.xtr=None
        self.Beta=None
        self.T0=None
        self.fix1_conversion=[]
        self.fix2_conversion=[]
        self.fix_aux_conversion=[]
        self.d_a1=0
        self.p1=0
        self.aVy=None
        self.Vy=None
        self.Fr=None
        self.KAS=None
        self.OFW=None
        self.method_used=None 
        self.isoTables=None    
        self.resultado=None   
        self.methods=""
        self.compensation_inicio=None
        self.compensation_error='r_Lin'
        self.ace=None
        self.g_a=None
        self.compensation=None
        self.ap2=None
        self.Tp2=None
        self.tp2=None
        self.canvas=None
        self.encoding_final=None
        self.x=None
        self.y=None
        self.datos_array=None
        self.DFlis=None
        self.number_max=0
        self.number_min=0
        self.nombres_aux=[]
        self.one_step_aux=[]
        self.conversion_aux=0   
        self.menu_start=None
        self.menu_start2=None
        self.compensation_alphaE=None
        self._configurar_menu()
        self.etiqueta=None
        self.control=None
        
       
        """
        This section defines our main container and the two containers within it.
        The header container will hold the buttons to be used, and the graphics 
        container will hold the necessary graphics so that the program user can
        make the appropriate decisions.
        
        """
        
        # ttk for bootstarp
        
        self.frame_contenedor = ttk.Frame(self) 
        self.frame_contenedor.pack(fill="both", expand=True)
        
        self.frame_header = ttk.LabelFrame(self.frame_contenedor, text="Toolbar", padding=10, bootstyle="primary")
        self.frame_header.pack(side="top", fill="x", padx=10, pady=5)
        
        self.frame_grafico = ttk.LabelFrame(self.frame_contenedor, text="Overview", padding=10, bootstyle="info")
        self.frame_grafico.pack(side="bottom", fill="both", expand=True, padx=10, pady=5)
        
        estilo = ttk.Style()
        
        estilo.configure("Gigante.TLabel", font=("", 34, "bold"))
        
        self.etiqueta = ttk.Label(
            self.frame_grafico, 
            text="Picnik desktop edition", 
            style="Gigante.TLabel",  # link style
            bootstyle="light"
        )
        self.etiqueta.pack(expand=True)
        

        
        self.config_fases = {
            1: [("Open Files", self.open_files)],
            2: [("time(m) vs TG(%)", self.g1), ("time(m) vs DGT(%/m)",self.g2),("time(m) vs dT/dt(K/m)", self.g3),("temp[K] vs TG[%] ", self.g4),("temp[K] vs DTG[%/m]", self.g5),("temp[K] vs dT/dt[K/m]", self.g6)],
            3: [("Thermogram", self.g4), ("Enter temperatures", self.input_temp_i)],
            4: [("Conversion", self.conversion)],
            5: [("Isoconversion step", self.input_data_isoconversion),    ("Isoconversion", self.mostrar_opciones)],
            6:[("Options of activation energy", self.methods_menu),("Select activation energy method", self.chose_method_isoconversion),("Export activation energy data", self.export_data_ea)],
            7: [("Input data compensation", self.input_date_compensation), ("ln A vs α", self.ver_compensation_alpha),("lnA=m*E + b", self.ver_compensation_E),("Summary", self.ver_compensation_report),("save data", self.export_compensation_report)],
            8: [("Reconstruccion", self.ver_recontruction)],
            9: [("Export Kinetic triplet data", self.save_kinetic_triplet)],
            }

        self.actualizar_botones()
        
        self.protocol("WM_DELETE_WINDOW",self.function_exit)  

    def function_exit(self):
         """
         This method closes the application.
         """
         
         if messagebox.askyesno("Quit", "Do you want to exit the application?"):
             self.destroy()
             sys.exit()    
    
   
    
    def tema_claro(self):
        self.style.theme_use("flatly")
        self.tema="flatly"
        
        if (self.fase_actual.get() == 1) and (  self.one_step==[]) :
            if hasattr(self, 'etiqueta') and self.etiqueta.winfo_exists():
                self.etiqueta.destroy()
            self.etiqueta = ttk.Label(
                self.frame_grafico, 
                text="Picnik desktop edition", 
                font=("", 28, "bold"),
                bootstyle="dark"    
            )
            self.etiqueta.pack(expand=True) 
        else:
            if hasattr(self, 'etiqueta') and self.etiqueta.winfo_exists():
                self.etiqueta.config(bootstyle="dark")   
       
    def tema_oscuro(self):
        self.style.theme_use("darkly")
        self.tema="darkly"
        if (self.fase_actual.get() == 1) and (  self.one_step==[]) :
            if hasattr(self, 'etiqueta') and self.etiqueta.winfo_exists():
                self.etiqueta.destroy()
            self.etiqueta = ttk.Label(
                self.frame_grafico, 
                text="Picnik desktop edition", 
                font=("", 28, "bold"),
                bootstyle="light"    
            )
            self.etiqueta.pack(expand=True) 
        else:
            if hasattr(self, 'etiqueta') and self.etiqueta.winfo_exists():
                self.etiqueta.config(bootstyle="light")

    def tema_oscuro2(self):
        self.style.theme_use("cyborg")
        self.tema="cyborg"
        if (self.fase_actual.get() == 1) and (  self.one_step==[]) :
            if hasattr(self, 'etiqueta') and self.etiqueta.winfo_exists():
                self.etiqueta.destroy()
            self.etiqueta = ttk.Label(
                self.frame_grafico, 
                text="Picnik desktop edition", 
                font=("", 28, "bold"),
                bootstyle="light"    
            )
            self.etiqueta.pack(expand=True) 
        else:
            if hasattr(self, 'etiqueta') and self.etiqueta.winfo_exists():
                self.etiqueta.config(bootstyle="light")


    def _configurar_menu(self):
        
        """
        This method creates the navigation menu
        """
        menubar = ttk.Menu(self)
        self.config(menu=menubar)
        
        # --- menu files ---
        # CORRECCIÓN: Usar tk.Menu, no ttk.Menu
        menu_files = tk.Menu(menubar, tearoff=0) 
        menubar.add_cascade(label="Files", menu=menu_files)
        menu_files.add_command(label="Open Files", command=self.open_files)
        menu_files.add_separator()
        menu_files.add_command(label="Exit", command=self.function_exit)

        
        menu_theme = tk.Menu(menubar, tearoff=0)
        menubar.add_cascade(label="Theme", menu=menu_theme)
        menu_theme.add_command(label="Light", command=self.tema_claro)
        menu_theme.add_command(label="Dark", command=self.tema_oscuro)
        menu_theme.add_command(label="Cyborg", command=self.tema_oscuro2)
        
                
      

        # --- menu images ---
        menu_images = ttk.Menu(menubar, tearoff=0)
        menubar.add_cascade(label="Images", menu=menu_images)
        menu_images.add_command(label="Save Image", command=self.save_image_picnik)

        # --- menu help ---
        menu_help = ttk.Menu(menubar, tearoff=0)
        menubar.add_cascade(label="Help", menu=menu_help)
        menu_help.add_command(label="About", command=self.about_picnik)
        menu_help.add_command(label="Tutorial", command=self.function_tutorial)

    def actualizar_botones(self):
        """
        clean and create action and navigation buttons
        previous button, next button and restore button
        """
        for widget in self.frame_header.winfo_children():
            widget.destroy()

        fase = self.fase_actual.get()
        
       
        total_buttoms = 0
        if fase > 1:
            total_buttoms += 1  # buttom "Previous"
            
        if fase in self.config_fases:
            total_buttoms += len(self.config_fases[fase])  # actions buttom
            
        total_buttoms += 1  # buttom "Next" o "restart"
        
        # font size, padding size, margin size
        padding_y = 6   
        if total_buttoms <= 3:
            tamano_letra = 11
            padding_x = 12
            margen_x = 5
        elif 4 <= total_buttoms <= 5:
            tamano_letra = 9
            padding_x = 8
            margen_x = 4
        else:
            tamano_letra = 8
            padding_x = 1
            margen_x = 1

        # configure ttkbootstrap and font size
        estilo = ttk.Style()
        estilo.configure("primary.TButton", font=("", tamano_letra))
        estilo.configure("secondary.TButton", font=("", tamano_letra,))
        estilo.configure("success.TButton", font=("", tamano_letra))
        estilo.configure("danger.TButton", font=("", tamano_letra))

   
        # button previous (second phase)
        if fase > 1:
            ttk.Button(self.frame_header, text="<< Previous", 
                       command=self.go_previous,
                       padding=(padding_x, padding_y),
                       bootstyle="secondary",
                       cursor="hand2").pack(side="left", padx=margen_x)

        # --- actions buttons-
        if fase in self.config_fases:
            for texto, comando in self.config_fases[fase]:
                ttk.Button(self.frame_header, text=texto, 
                           command=comando,
                           padding=(padding_x, padding_y),
                           bootstyle="primary",
                           cursor="hand2").pack(side="left", padx=margen_x)

        # --- button next ---
        if fase < len(self.config_fases):
            ttk.Button(self.frame_header, text="Next >>", 
                       command=self.go_next,
                       padding=(padding_x, padding_y),
                       bootstyle="success",
                       cursor="hand2").pack(side="right", padx=margen_x)
        else:
            # reset button
            ttk.Button(self.frame_header, text="Restart", 
                       command=self.reiniciar,
                       padding=(padding_x, padding_y),
                       bootstyle="danger",
                       cursor="hand2").pack(side="right", padx=margen_x)

    def go_next(self):
        """
        This method takes us to the next screen
        """
        self.fase_actual.set(self.fase_actual.get() + 1)
        self.actualizar_botones()
        self.control=1
    
    def go_previous(self):
        """
        This method takes us to the previous screen
        """
        self.fase_actual.set(self.fase_actual.get() - 1)
        self.actualizar_botones()
    
    def reiniciar(self):
        """
        This method resets all my variables to restart the application.
        """
        
        for widget in self.frame_grafico.winfo_children():
            widget.destroy()
        
        self.fase_actual.set(1)
        self.actualizar_botones()
        self.fig = None
        """
        # SOLUCIÓN: Cambiado a ttk.Label con bootstyle="light" para mantener el modo oscuro
        etiqueta = ttk.Label(
            self.frame_grafico, 
            text="Picnik desktop edition", 
            font=("Helvetica", 34, "bold"), # Usamos Helvetica para evitar fallos entre Windows y Linux
            bootstyle="light" # Fuerza a que las letras se mantengan blancas/claras premium
        )
        
        etiqueta.pack(expand=True)
        
        """
        if hasattr(self, 'etiqueta') and self.etiqueta is not None:
            self.etiqueta.destroy()
            
   
  
     
        
        """
        reset variables
        """  
        
        self.one_step=[]
        self.numero_de_archivos=0
        self.fig=None
        self.xtr=None
        self.Beta=None
        self.T0=None
        self.fix1_conversion=[]
        self.fix2_conversion=[]
        self.fix_aux_conversion=[]
        self.d_a1=0
        self.p1=0
        self.aVy=None
        self.Vy=None
        self.Fr=None
        self.KAS=None
        self.OFW=None
        self.method_used=None 
        self.isoTables=None    
        self.resultado=None   
        self.methods=""
        self.compensation_inicio=None
        self.compensation_error='r_Lin'
        self.ace=None
        self.g_a=None
        self.compensation=None
        self.ap2=None
        self.Tp2=None
        self.tp2=None
        self.canvas=None
        self.encoding_final=None
        self.x=None
        self.y=None
        self.datos_array=None      
        self.DFlis=None
        self.number_max=0
        self.number_min=0
        self.nombres_aux=[]
        self.resultado=[]
        self.conversion_aux=0
        self.menu_start=None
        self.menu_start2=None
        self.compensation_alphaE=None
        self._configurar_menu()
        self.etiqueta=None
        self.control=None
        
        if self.tema == "darkly":
            self.etiqueta = ttk.Label(
                self.frame_grafico, 
                text="Picnik desktop edition", 
                font=("", 28, "bold"),
                bootstyle="light"    
            )
            self.etiqueta.pack(expand=True) 
        elif self.tema == "flatly":
            self.etiqueta = ttk.Label(
                self.frame_grafico, 
                text="Picnik desktop edition", 
                font=("", 28, "bold"),
                bootstyle="dark"    
            )
            self.etiqueta.pack(expand=True) 
        else:
            self.etiqueta = ttk.Label(
                self.frame_grafico, 
                text="Picnik desktop edition", 
                font=("", 28, "bold"),
                bootstyle="dark"    
            )
            self.etiqueta.pack(expand=True)   
                
    
    def detect_encoding(self,file, num_bytes=10000):
        """ 
        This method detects the encoding,which is required as 
        a parameter within the view_graphs method.
        """

        with open(file, 'rb') as f:
            raw_data = f.read(num_bytes)
        result = chardet.detect(raw_data)
        return result['encoding'], result['confidence']

    def open_files(self): 
        """ 
        The user is prompted to upload files that are used to process and 
        generate new information and graphics through Picnik.
        """
            
        self.one_step_aux.clear()
        
        try:
            files = filedialog.askopenfilenames(
                filetypes=[("valid files", "*.csv *.txt")]
            )
        
            # files validation
            if len(files) > 1:
                self.one_step_aux.clear()
                self.one_step_aux.extend(files)
                for file in self.one_step_aux:
                    print("-------------------")
                
                # save number files
                self.numero_de_archivos = len(files)    
            else:
                messagebox.showinfo(
                    title="Two or more files, please",
                    message="Two or more files, please"
                )
                self.one_step_aux.clear()
                return # detiene la función aquí si no hay archivos válidos
           
            # validación del número de columnas solo corre si hay mas de un archivo
            estado = 0
            for file in self.one_step_aux:
                try:
        
                    codificacion, confianza = self.detect_encoding(file) 
                      
                    # 3. read colums for detect encoding
                    df = pd.read_csv(file, nrows=0, skipinitialspace=True, encoding=codificacion, sep=r'[\t,;]+', engine='python')
                    columnas = df.shape[1]
                        
                    if columnas != 3:
                        estado = 1
                        break 
                        
                except Exception as e:
                    print(f"Error al verificar columnas en {file}: {e}")
                    estado = 1
                    break
        
            if estado == 0: 
                self.view_graphs()
            else:
                messagebox.showerror(
                    title="Error file",
                    message="Number of columns incorrect or unreadable file. Please check your file."
                )
                
        except Exception as e:
        
            messagebox.showerror("error", f"error open files: {e}")
                
                

    def draw_fig(self):
        """ 
        Clean the canvas and draw the corresponding figure
        """
        for widget in self.frame_grafico.winfo_children():
                    widget.destroy()

        # canvas configure
        self.canvas = FigureCanvasTkAgg(self.fig, master=self.frame_grafico)
        self.canvas.draw()
  
        # navigation toolbar
        toolbar = NavigationToolbar2Tk(self.canvas, self.frame_grafico, pack_toolbar=False)
        toolbar.update()
        color_fondo = "#212529"       # backgroud dark
        color_texto = "#ffffff"       # font white
        
        toolbar.config(background=color_fondo)
        for elemento in toolbar.winfo_children():
            try:
                elemento.config(background=color_fondo, foreground=color_texto)
            except Exception:
                # Si el elemento no acepta texto (como los separadores), solo cambia su fondo
                elemento.config(background=color_fondo)

        # Toolbar at the bottom and chart at the top
        toolbar.pack(side=tk.BOTTOM, fill=tk.X)
        self.canvas.get_tk_widget().pack(side=tk.TOP, fill=tk.BOTH, expand=True)

        
                        
    #the six initial main figures are draw
    def view_graphs(self):
            """
            It is verified that the files have the same encoding; if so,
            the encoding is passed to the `read files` method; otherwise, an error message is sent.
            A `Data extraction` class object is created, and
            the variables `fig`, `Beta`, `T0`, and `DFlist` are received, drawing six
            support graphs for analysis and calculations.
            """
            
            try:
                # verification of selected files
                if not hasattr(self, 'one_step_aux') or not self.one_step_aux:
                    messagebox.showwarning("Warning", "No files selected to process.")
                    return

                # --- detección de encodings ---
                codificaciones = []
                for file in self.one_step_aux:
                    encoding, conf = self.detect_encoding(file)
                    if encoding:
                        codificaciones.append(encoding)
                    else:
                        messagebox.showerror("Error", f"The encoding could not be detected: {file}")
                        return
            
                encoding_set = set(codificaciones)
                if len(encoding_set) == 1:
                    self.encoding_final = encoding_set.pop()
                else:
                    messagebox.showerror(
                        "Encoding incompatibility",
                        "The files have different encodings:\n" + 
                        "\n".join(f"{f} => {e}" for f, e in zip(self.one_step_aux, codificaciones))
                    )
                    return 

               # data extraction and figure generation
                self.xtr = pnk.DataExtraction()
                
                # Function that isolates the file name to avoid including periods in the extension or paths
                
                def extraer_numero_de_ruta(ruta_completa):
                    
                    # extract only the final name
                    nombre_archivo = os.path.basename(ruta_completa)
                   
                    # remove the extension
                    nombre_sin_extension, _ = os.path.splitext(nombre_archivo)
                    
                    # extract only digits and periods from the clean name
                    solo_numeros = "".join(re.findall(r'[0-9.]', nombre_sin_extension))
                    try:
                        return float(solo_numeros)
                    except ValueError:
                        return float('inf') # Manda al final si algo sale mal

                #ordering
                self.one_step = sorted(self.one_step_aux, key=extraer_numero_de_ruta)

                self.fig, self.Beta, self.T0, self.DFlis = self.xtr.read_files(self.one_step, encoding=self.encoding_final)
              
                #review each DataFrame in the list
                array_DFlis = []
                limite_archivos = min(len(self.DFlis), self.numero_de_archivos)
                
                for i in range(limite_archivos):
                    try:
                        # Extract the maximum from column 4, safely converting to numeric
                        
                        valores_numericos = pd.to_numeric(self.DFlis[i].iloc[:, 4], errors='coerce')
                        max_valor = valores_numericos.max()
                        min_valor = valores_numericos.min()
                        if pd.notna(max_valor):
                            array_DFlis.append(int(max_valor))
                        if pd.notna(min_valor):
                            array_DFlis.append(int(min_valor))
                            
                            
                    except Exception:
                        pass
                
                if array_DFlis:
                    self.number_max = max(array_DFlis)
                    self.number_min = min(array_DFlis)
                    
                else:
                    self.number_max = 0
                    self.number_min = 0
                
                self.draw_fig()

            except Exception as e:
                # unespected error
                messagebox.showerror("error", f" Non-numeric data was detected, please check your files,  {str(e)}")

    

    #--------------------------------------------------------------------------
   
            
    def view_limits(self):
            """
            It is verified that the files have the same encoding; if so,
            the encoding is passed to the `read files` method; otherwise, an error message is sent.
            A `Data extraction` class object is created, and
            the variables `fig`, `Beta`, `T0`, and `DFlist` are received, drawing six
            support graphs for analysis and calculations.
            """
            
            try:
              
               # data extraction and figure generation
                self.xtr = pnk.DataExtraction()
                
                # Function that isolates the file name to avoid including periods in the extension or paths
                
                def extraer_numero_de_ruta(ruta_completa):
                    
                    # extract only the final name
                    nombre_archivo = os.path.basename(ruta_completa)
                   
                    # remove the extension
                    nombre_sin_extension, _ = os.path.splitext(nombre_archivo)
                    
                    # extract only digits and periods from the clean name
                    solo_numeros = "".join(re.findall(r'[0-9.]', nombre_sin_extension))
                    try:
                        return float(solo_numeros)
                    except ValueError:
                        return float('inf') # Manda al final si algo sale mal

                #ordering
                self.one_step = sorted(self.one_step_aux, key=extraer_numero_de_ruta)

                self.fig, self.Beta, self.T0, self.DFlis = self.xtr.read_files(self.one_step, encoding=self.encoding_final)
              
            
                #review each DataFrame in the list
                array_DFlis = []
                limite_archivos = min(len(self.DFlis), self.numero_de_archivos)
                
                for i in range(limite_archivos):
                    try:
                        # Extract the maximum from column 4, safely converting to numeric
                        
                        valores_numericos = pd.to_numeric(self.DFlis[i].iloc[:, 4], errors='coerce')
                        max_valor = valores_numericos.max()
                        min_valor = valores_numericos.min()
                        if pd.notna(max_valor):
                            array_DFlis.append(int(max_valor))
                        if pd.notna(min_valor):
                            array_DFlis.append(int(min_valor))
                            
                            
                    except Exception:
                        pass
                
                if array_DFlis:
                    self.number_max = max(array_DFlis)
                    self.number_min = min(array_DFlis)
                    
                else:
                    self.number_max = 0
                    self.number_min = 0
                
                #self.draw_fig()
                
            except Exception as e:
                # unespected error
                messagebox.showerror("error", f" Non-numeric data was detected, please check your files,  {str(e)}")        

    #--------------------------------------------------------------------------
    
    

    #------------view images-------------------------------
    

    def g1(self):
        """
        generate image one time vs TG
        """
        try:       
            self.fig=self.xtr.plot_data(x_data='time',y_data='TG', x_units='min', y_units='%')   
            self.draw_fig()
        except:
            messagebox.showerror("Error", "There is no data to generate the figure")
        
    def g2(self):
        """
        generate image two time vs DGT
        """
        try:
            self.fig=self.xtr.plot_data(x_data='time',y_data='DTG', x_units='min', y_units='%/min')   
            self.draw_fig()
        except:
            messagebox.showerror("Error", "There is no data to generate the figure")
        
    def g3(self):
        """
        generate image three time vs dT/dt
        """
        try:           
            self.fig=self.xtr.plot_data(x_data='time',y_data='dT/dt', x_units='min', y_units='K/min')   
            self.draw_fig()
        except:
            messagebox.showerror("Error", "There is no data to generate the figure")
        
    def g4(self):
        """
        generate image four temperature vs TG
        """
        try:
            self.fig=self.xtr.plot_data(x_data='temperature',y_data='TG', x_units='K', y_units='%')   
            self.draw_fig()
        except:
            messagebox.showerror("Error", "There is no data to generate the figure")
        
    def g5(self):
        """
        generate image five temperature vs DTG
        """
        try:            
            self.fig=self.xtr.plot_data(x_data='temperature',y_data='DTG', x_units='K', y_units='%/min')   
            self.draw_fig()
        except:
            messagebox.showerror("Error", "There is no data to generate the figure")
            
    def g6(self):
        """
        generate image six temperature vs dT/dt
        """
        try:
            self.fig=self.xtr.plot_data(x_data='temperature',y_data='dT/dt', x_units='K', y_units='K/min')   
            self.draw_fig()
        except:
            messagebox.showerror("Error", "There is no data to generate the figure")
        
    def input_temp_i(self):
        """
        The user enters initial and final temperature values that are saved in two arrays that the 
        Conversion function will need
        """
       
        if self.one_step != []:
            
            self.view_limits()
            
            ventana = tk.Toplevel()
            ventana.title("Enter limits")
            ventana.geometry("440x340")
            arreglo2 = []
            
            def solo_enteros(nuevo_texto):
                return nuevo_texto == "" or nuevo_texto.isdigit()
            
            validar = ventana.register(solo_enteros)
            
            main_frame = ttk.Frame(ventana)
            main_frame.pack(fill="both", expand=True)
            canvas = tk.Canvas(main_frame)
            
            label1 = ttk.Label(main_frame, text="initial temperature(K)                   end temperature(K)")
            label1.pack()
            
            scrollbar = ttk.Scrollbar(main_frame, orient="vertical", command=canvas.yview)
            frame = ttk.Frame(canvas)
            frame.bind("<Configure>", lambda e: canvas.configure(scrollregion=canvas.bbox("all")))
            canvas.create_window((0, 0), window=frame, anchor="nw")
            canvas.configure(yscrollcommand=scrollbar.set)
            canvas.pack(side="left", fill="both", expand=True)
            scrollbar.pack(side="right", fill="y")
            
            entries_a1, entries_a2 = [], []
            vars_a1, vars_a2 = [], []
            
            # limits
            limite_medio_inf = int((self.number_min + self.number_max) / 2)
            limite_medio_sup = limite_medio_inf + 1
            
            def crear_fila(i):
                fila = ttk.Frame(frame)
                fila.grid(row=i, column=0, pady=5, padx=10, sticky="ew")
                ttk.Label(fila, text=f"β {self.Beta[i].round(2)}", width=10).grid(row=0, column=0)
                
                
                val_inicial_1 = int((self.number_min + ((self.number_min + self.number_max) / 2)) / 2)
                var1 = tk.IntVar(value=val_inicial_1)
                
                entry1 = ttk.Entry(fila, width=5, validate="key", validatecommand=(validar, "%P"))
                entry1.grid(row=0, column=2)
                entry1.insert(0, str(val_inicial_1))
                
                def mover_scale1(val):
                    v = int(float(val))
                    entry1.delete(0, tk.END)
                    entry1.insert(0, str(v))
                    var1.set(v)
                    
                scale1 = ttk.Scale(fila, from_=self.number_min, to=limite_medio_inf, orient="horizontal", variable=var1, command=mover_scale1)
                scale1.grid(row=0, column=1, padx=5, sticky="ew")
                
                def update_scale1(event):
                    t = entry1.get()
                    if t.isdigit():
                        val = int(t)
                        if self.number_min <= val <= limite_medio_inf:
                            var1.set(val)
                            
                entry1.bind("<KeyRelease>", update_scale1)
                
                val_inicial_2 = int((((self.number_min + self.number_max) / 2) + self.number_max)/2)
                var2 = tk.IntVar(value=val_inicial_2)
                
                entry2 = ttk.Entry(fila, width=5, validate="key", validatecommand=(validar, "%P"))
                entry2.grid(row=0, column=4)
                entry2.insert(0, str(val_inicial_2))
                
                def mover_scale2(val):
                    v = int(float(val))
                    entry2.delete(0, tk.END)
                    entry2.insert(0, str(v))
                    var2.set(v)
                    
                scale2 = ttk.Scale(fila, from_=limite_medio_sup, to=self.number_max, orient="horizontal", variable=var2, command=mover_scale2)
                scale2.grid(row=0, column=3, padx=5, sticky="ew")
                
                def update_scale2(event):
                    t = entry2.get()
                    if t.isdigit():
                        val = int(t)
                        if limite_medio_sup <= val <= self.number_max:
                            var2.set(val)
                            
                entry2.bind("<KeyRelease>", update_scale2)
                
                vars_a1.append(var1)
                vars_a2.append(var2)
                entries_a1.append(entry1)
                entries_a2.append(entry2)
            
            for i in range(self.numero_de_archivos): 
                crear_fila(i)
                
            # validando datos
            def obtener():
                
                arreglo2.clear() 
                
                for i in range(self.numero_de_archivos):
                    val1_str = entries_a1[i].get()
                    val2_str = entries_a2[i].get()
                    arreglo2.append(val2_str)
                    
                    #campos vacíos
                    if val1_str == "" or val2_str == "":
                        messagebox.showwarning("Error", f"Empty box in the row {i+1}")
                        arreglo2.clear()
                        return
                    
                    # limit
                    v1, v2 = int(val1_str), int(val2_str)
                    if not (self.number_min <= v1 <= limite_medio_inf):
                        messagebox.showerror("Out of range", f"In row {i+1}, the first value ({v1}) must be between {self.number_min} and {limite_medio_inf}.")
                        arreglo2.clear()
                        return
                    if not (limite_medio_sup <= v2 <= self.number_max):
                        messagebox.showerror("Out of range", f"In row {i+1}, the second value ({v2}) must be between {limite_medio_sup} and {self.number_max}.")
                        arreglo2.clear()
                        return
                    if not (v1 < v2):
                        messagebox.showerror("Out of range", f"In row {i+1}, the second value {v2} must be strictly greater than the first value {v1}")
                        arreglo2.clear()
                        return
                    
                self.fix1_conversion = [v.get() for v in vars_a1]
                
                
                self.fix2_conversion = [int(v) for v in arreglo2 if v.isdigit()]
                
                messagebox.showinfo("Saved", "All values are within range and have been saved.")
                ventana.destroy()
                
            boton_frame = ttk.Frame(ventana)
            boton_frame.pack(fill="x")
            ttk.Button(boton_frame, text="Save values",style="primary", command=obtener).pack(pady=10)
            
        else:
            messagebox.showinfo("open files", "open files, please")

         
         
   
    def conversion(self):
        """
        the picnik conversion function is executed
        """
        if self.one_step == []:
            messagebox.showinfo("open files", "open files, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input initial temperature, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input final temperature, please")
            
        else:
            try:
               
                self.fig=self.xtr.Conversion(self.fix1_conversion,self.fix2_conversion)
                self.conversion_aux=1
                self.draw_fig()
    
            except Exception as e:
                
                messagebox.showerror("Unexpected error", f"Details: {str(e)}")

    #-----------------------------------------------------------------------------------#

    def input_data_isoconversion(self):          #----revisar--------
        """
        The user saves the Δα value that they deem appropriate.
        """
        if self.one_step == []:
            messagebox.showinfo("open files", "open files, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input initial temperature, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input final temperature, please")
        elif self.conversion_aux==0:
            messagebox.showinfo("conversion", "execute conversion, please")
              
        else:
            fuente = ("", 12, "bold")
            
            # ttk extends 'darkly'
            ventana_isoconversion = ttk.Toplevel(self)
            ventana_isoconversion.title("Input data")
            ventana_isoconversion.geometry("400x320")
            ventana_isoconversion.resizable(False, False)
            ventana_isoconversion.configure(padx=20, pady=20)
    
            # --- d_a ---
            def validar_entrada(texto_nuevo):
                # allows you to delete the field completely
                if texto_nuevo == "":
                    return True
                    
                # only digits and at most one decimal point
                if not (all(char.isdigit() or char == "." for char in texto_nuevo) and texto_nuevo.count(".") <= 1):
                    return False # Bloquea letras, espacios o un segundo punto
                    
                # maximum 3 numbers after the period
                if "." in texto_nuevo:
                    parte_decimal = texto_nuevo.split(".")[1]
                    if len(parte_decimal) > 3:
                        return False # bloquea el cuarto decimal de inmediato
            
                return True
    
            # registered the function in the Tkinter window
            v_cmd = ventana_isoconversion.register(validar_entrada)
            
            # extend darkly
            #ttk.Label(ventana_isoconversion, text="Δα = ", font=fuente, bootstyle="darkly").pack(pady=10)
            ttk.Label(ventana_isoconversion, text="Δα = ", font=fuente).pack(pady=10)
            
            valor_inicio = tk.DoubleVar(value=0.005)
        
            spinbox_rango = ttk.Spinbox(
                ventana_isoconversion, 
                from_=0, 
                to=0.99, 
                increment=0.001, 
                state="normal",
                textvariable=valor_inicio, 
                font=fuente,
                validate="key", 
                validatecommand=(v_cmd, '%P')
            )
            spinbox_rango.pack(pady=10, fill="x")
                            
            # --- save data and exit ---
            def guardar_y_cerrar():
                self.d_a1 = valor_inicio.get()
                ventana_isoconversion.destroy()
    
            # --- button ok ---
            button_algo = ttk.Button(
                ventana_isoconversion, 
                text="OK", 
                command=guardar_y_cerrar,
                bootstyle="primary",
                cursor="hand2"
            )
            button_algo.pack(side=tk.BOTTOM, fill="x", pady=(20, 0))
        
        
    def mostrar_opciones(self):
        """ 
        This method is responsible for showing the user a preview 
        of the time, temperature, and conversion rate files.
        """
        
        if self.one_step == []:
            messagebox.showinfo("open files", "open files, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input initial temperature, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input final temperature, please")
        elif self.conversion_aux==0:
            messagebox.showinfo("conversion", "execute conversion, please")
        else:
            
            # --- if it already exists, it does nothing.---
            if hasattr(self, 'menu_obj') and self.menu_obj.winfo_exists():
                return
        
            """
            self.opcion_var = tk.StringVar(self.frame_header)
            self.opcion_var.set("temperature")
            
            # we disable the "save" button every time the menu option changes.
            # the trace command detects when the user selects something new.
            self.opcion_var.trace_add("write", lambda *args: self.btn_save.config(state="disabled"))
        
            self.menu_obj = tk.OptionMenu(self.frame_header, self.opcion_var, "time", "temperature", "conversion rate")
            self.menu_obj.pack(side="left", padx=10)
            """
            
            #-------------------------
                        
                      
            
            # tk extend tkinter
            self.opcion_var = tk.StringVar(self.frame_header)
            self.opcion_var.set("temperature")
            self.opcion_var.trace_add("write", lambda *args: self.btn_save.config(state="disabled"))
            
            opciones = ["time", "temperature", "conversion rate"]
            
            self.menu_obj = ttk.OptionMenu(
                self.frame_header, 
                self.opcion_var, 
                self.opcion_var.get(),
                *opciones,
                #bootstyle="darkly"
            )
            self.menu_obj.pack(side="left", padx=10)

        
            def ejecutar_accion(tipo):
                seleccion = self.opcion_var.get()
                if tipo == "preview":
                    # if you press view, we activate the save button
                    self.btn_save.config(state="normal")
                    
                    if seleccion == "time": self.ver_timeAdvIsoDF()
                    elif seleccion == "temperature": self.ver_TempAdvIsoDF()
                    elif seleccion == "conversion rate": self.ver_diffAdvIsoDF()
                else: # tipo == "save"
                    if seleccion == "time": self.export_timeAdvIsoDF()
                    elif seleccion == "temperature": self.export_TempAdvIsoDF()
                    elif seleccion == "conversion rate": self.export_diffAdvIsoDF()
        
            # view button (always active)
            self.btn_see = ttk.Button(self.frame_header, text="preview", 
                                     command=lambda: ejecutar_accion("preview"), width=10)
            self.btn_see.pack(side="left", padx=5)
        
            # save button (starts off)
            self.btn_save = ttk.Button(self.frame_header, text="save", 
                                      command=lambda: ejecutar_accion("save"), 
                                      width=10, state="disabled")
            self.btn_save.pack(side="left", padx=5)


    def ver_TempAdvIsoDF(self):
        """
        View a preview of the temperature data
        """
        self.xtr = pnk.DataExtraction()       
        self.fig, self.Beta, self.T0, self.number_max = self.xtr.read_files(self.one_step, encoding=self.encoding_final)    
        self.xtr.Conversion(self.fix1_conversion,self.fix2_conversion)
        self.isoTables=None
        
        try:
            # frame clean
            for widget in self.frame_grafico.winfo_children():
                widget.destroy()

            # #get data and ensure that self.isoTables is a dataFrame
            self.isoTables = self.xtr.Isoconversion(d_a=self.d_a1)
            # if it's a tuple, we extract the array
            text_area = tk.Text(self.frame_grafico, font=("Consolas", 10), padx=10, pady=10)
            # insert text
            text_area.insert(tk.END, str(self.isoTables[0])) 
            
            text_area.config(state=tk.DISABLED)
            text_area.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)

        except Exception as e:
            messagebox.showerror("error", f"there is no data to display  {e}")
            
        self.fig=None


    def export_TempAdvIsoDF(self):
        """
        exports temperature data
        """
        try:
           if self.isoTables != None:
           
               filepath = filedialog.asksaveasfilename(
                   defaultextension=".csv",
                   filetypes=[("Archivo CSV", "*.csv")],
                   title="Guardar tabla de resultados"
               )
    
               if filepath:
                   self.isoTables[0].index.name = "alpha"
                   self.isoTables[0].index = np.trunc(self.isoTables[0].index * 1e6) / 1e6
                   self.isoTables[0].to_csv(filepath, index=True, encoding='utf-8-sig', sep=',')
           else:
               messagebox.showerror("error", "there is no data to save")
                 
        except Exception as e:
            messagebox.showerror("error", f"error unexpected {e}")
         
        
    def ver_timeAdvIsoDF(self):
        """
        View a preview of the time data
        """
    
        self.xtr = pnk.DataExtraction()       
        self.fig, self.Beta, self.T0, self.number_max  = self.xtr.read_files(self.one_step, encoding=self.encoding_final)    
        self.xtr.Conversion(self.fix1_conversion,self.fix2_conversion)
        self.isoTables=None
        
        try:
            # frame clean
            for widget in self.frame_grafico.winfo_children():
                widget.destroy()

            # obtain data and ensure that self.isoTables is a DataFrame
            self.isoTables = self.xtr.Isoconversion(d_a=self.d_a1)
            # if it's a tuple, we extract the array
            text_area = tk.Text(self.frame_grafico, font=("Consolas", 10), padx=10, pady=10)
            # insert the formatted text
            text_area.insert(tk.END, str(self.isoTables[1])) 
            text_area.config(state=tk.DISABLED)
            text_area.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)

        except Exception as e:
            messagebox.showerror("error", f"there is no data to display {e}")
            
        self.fig=None


    def export_timeAdvIsoDF(self):
        """
        exports time data
        """
        
        try:
           if self.isoTables != None:
           
               filepath = filedialog.asksaveasfilename(
                   defaultextension=".csv",
                   filetypes=[("Archivo CSV", "*.csv")],
                   title="Guardar tabla de resultados"
               )
    
               if filepath:
                   self.isoTables[1].index.name = "alpha"
                   self.isoTables[1].index = np.trunc(self.isoTables[1].index * 1e6) / 1e6
                   self.isoTables[1].to_csv(filepath, index=True, encoding='utf-8-sig', sep=',')
                   
           else:
               messagebox.showerror("error", "there is no data to save")
                 
        except Exception as e:
            #messagebox.showerror("error", "no hay datos a guardar")
            messagebox.showerror("error", f"error unexpected  {e}")
         
        
            
    def ver_diffAdvIsoDF(self):
        """
        View a preview of the convertion rate data
        """

        self.xtr = pnk.DataExtraction()       
        self.fig, self.Beta, self.T0, self.number_max  = self.xtr.read_files(self.one_step, encoding=self.encoding_final)    
        self.xtr.Conversion(self.fix1_conversion,self.fix2_conversion)
        self.isoTables=None
        
        try:
            # clean frame
            for widget in self.frame_grafico.winfo_children():
                widget.destroy()

            # obtain data and ensure that self.isoTables is a DataFrame
            self.isoTables = self.xtr.Isoconversion(d_a=self.d_a1)
            # if it's a tuple, we extract the array
            text_area = tk.Text(self.frame_grafico, font=("Consolas", 10), padx=10, pady=10)
            # insert text
            text_area.insert(tk.END, str(self.isoTables[2])) 
            text_area.config(state=tk.DISABLED)
            text_area.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        except Exception as e:
            messagebox.showerror("error", f"there is no data to display {e}")
            

        self.fig=None


    def export_diffAdvIsoDF(self):
        """
        exports convertion rate data
        """
        
        try:
           if self.isoTables != None:
           
               filepath = filedialog.asksaveasfilename(
                   defaultextension=".csv",
                   filetypes=[("file csv", "*.csv")],
                   title="save results"
               )
    
               if filepath:
                   self.isoTables[2].index.name = "alpha"
                   self.isoTables[2].index = np.trunc(self.isoTables[2].index * 1e6) / 1e6
                   self.isoTables[2].to_csv(filepath, index=True, encoding='utf-8-sig', sep=',')
                   
           else:
               messagebox.showerror("error", "there is no data to save")
                 
        except Exception as e:
            messagebox.showerror("error", f"error unexpected {e}")
         
            
         
    #--------------------------------------------------------------------------        
             
    def function_input_advanced_vyazovkin_method(self,ventana_padre):
         """
         In this function, the user defines the minimum activation energy, 
         maximum activation energy, and percentile for the advanced Vyazovkin method.
         """
        
         # ttk extends darkly
         ventana_isoconversion = ttk.Toplevel(ventana_padre)
         ventana_isoconversion.title("Enter data")
         ventana_isoconversion.geometry("400x380")
         ventana_isoconversion.resizable(False, False)
         ventana_isoconversion.configure(padx=20, pady=20)
         
         fuente = ("", 12, "bold")
    
         #ttk.Label(ventana_isoconversion, text="Activate Energy Min = ", font=fuente, bootstyle="darkly").pack(pady=(5, 2))
         ttk.Label(ventana_isoconversion, text="Activate Energy Min = ", font=fuente).pack(pady=(5, 2))
         
         valor_inicio_x = tk.DoubleVar(value=5)
         
         spinbox_min = ttk.Spinbox(
             ventana_isoconversion, 
             from_=0, 
             to=250, 
             increment=0.5, 
             state="readonly", 
             textvariable=valor_inicio_x,
             font=fuente,
             width=20
         )
         spinbox_min.pack(pady=5, fill="x")
        
         #ttk.Label(ventana_isoconversion, text="Activate Energy Max = ", font=("", 10, "bold"), bootstyle="darkly").pack(pady=(10, 2))
         ttk.Label(ventana_isoconversion, text="Activate Energy Max = ", font=("", 10, "bold")).pack(pady=(10, 2))         
         valor_inicio_y = tk.DoubleVar(value=380)
         
         spinbox_max = ttk.Spinbox(
             ventana_isoconversion, 
             from_=250.05, 
             to=500, 
             increment=0.5, 
             state="readonly", 
             textvariable=valor_inicio_y,
             font=fuente,
             width=20
         )
         spinbox_max.pack(pady=5, fill="x")
        
         #ttk.Label(ventana_isoconversion, text="Percentile = ", font=("", 10, "bold"), bootstyle="darkly").pack(pady=(10, 2))
         ttk.Label(ventana_isoconversion, text="Percentile = ", font=("", 10, "bold")).pack(pady=(10, 2))
         valor_inicio_p = tk.DoubleVar(value=0.80)
         
         spinbox_p = ttk.Spinbox(
             ventana_isoconversion, 
             from_=0, 
             to=1, 
             increment=0.005, 
             state="readonly", 
             textvariable=valor_inicio_p,
             font=fuente,
             width=20
         )
         spinbox_p.pack(pady=5, fill="x")
        
         def guardar_y_cerrar():
             self.x = valor_inicio_x.get()
             self.y = valor_inicio_y.get()
             self.p1 = valor_inicio_p.get()
             ventana_isoconversion.destroy()
        

         button_algo = ttk.Button(
             ventana_isoconversion, 
             text="OK", 
             command=guardar_y_cerrar,
             bootstyle="primary",
             cursor="hand2"
         )
         button_algo.pack(side=tk.BOTTOM, fill="x", pady=(20, 0))
         
         ventana_padre.wait_window(ventana_isoconversion)

    
    
    def function_input_vyazovkin_method(self,ventana_padre):
         """
         In this function, the user defines the minimum and
         maximum activation energy for the Vyazovkin method.
         """
         ventana_isoconversion = ttk.Toplevel(ventana_padre)
         ventana_isoconversion.title("Enter data")
         ventana_isoconversion.geometry("400x320")
         ventana_isoconversion.resizable(False, False)
         ventana_isoconversion.configure(padx=20, pady=20)
         
         fuente = ("", 12, "bold")
        
         #ttk.Label(ventana_isoconversion, text="Activate Energy Min = ", font=("", 10, "bold"), bootstyle="darkly").pack(pady=(5, 2))
         ttk.Label(ventana_isoconversion, text="Activate Energy Min = ", font=("", 10, "bold")).pack(pady=(5, 2))
         valor_inicio_x = tk.DoubleVar(value=5)
         
         spinbox_min = ttk.Spinbox(
             ventana_isoconversion, 
             from_=0, 
             to=250, 
             increment=0.5, 
             state="readonly", 
             textvariable=valor_inicio_x,
             font=fuente,
             width=20
         )
         spinbox_min.pack(pady=5, fill="x")
        
         #ttk.Label(ventana_isoconversion, text="Activate Energy Max = ", font=("", 10, "bold"), bootstyle="darkly").pack(pady=(10, 2))
         ttk.Label(ventana_isoconversion, text="Activate Energy Max = ", font=("", 10, "bold")).pack(pady=(10, 2))
         valor_inicio_y = tk.DoubleVar(value=380)
         
         spinbox_max = ttk.Spinbox(
             ventana_isoconversion, 
             from_=250.05, 
             to=500, 
             increment=0.5, 
             state="readonly", 
             textvariable=valor_inicio_y,
             font=fuente,
             width=20
         )
         spinbox_max.pack(pady=5, fill="x")
        
         def guardar_y_cerrar():
             self.x = valor_inicio_x.get()
             self.y = valor_inicio_y.get()
             ventana_isoconversion.destroy()
        
         button_algo = ttk.Button(
             ventana_isoconversion, 
             text="OK", 
             command=guardar_y_cerrar,
             bootstyle="primary",
             cursor="hand2"
         )
         button_algo.pack(side=tk.BOTTOM, fill="x", pady=(20, 0))
         
         ventana_padre.wait_window(ventana_isoconversion)

    
    def methods_menu(self):
        """ 
        The user chooses the isoconversional methods they want to verify;
        then they see resulting graphs that they can use as support to know which method to follow.
        """
        
        
        if self.one_step == []:
            messagebox.showinfo("open files", "open files, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input initial temperature, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input final temperature, please")
        elif self.conversion_aux==0:
            messagebox.showinfo("conversion", "execute conversion, please")
        elif self.d_a1==0:
            messagebox.showinfo("delta", "input value delta, please")
        else:
            
             top = ttk.Toplevel(self.frame_contenedor)
             top.title("Select options")
             top.geometry("320x480") 
             
             top.configure(padx=20, pady=20) 
             
             nombres = ["Friedman", "Kissinger-Akahira-Sunose", "Flynn-Wall-Ozawa", "Advance-Vyazovkin", "Vyazovkin"]
             vars_opciones = [tk.IntVar(value=0) for _ in range(5)]
             botones_lista = []
             self.nombres_aux = []
         
             def toggle_boton(idx):
                 if vars_opciones[idx].get() == 0:
                     vars_opciones[idx].set(1)
                     # green bootstrap select
                     botones_lista[idx].config(bootstyle="success")
                 else:
                     vars_opciones[idx].set(0)
                     # gray bootstrap not select
                     botones_lista[idx].config(bootstyle="secondary")
         
             #ttk.Label(top, text="Click to mark:", font=("", 11, "bold"), bootstyle="darkly").pack(pady=10)
             ttk.Label(top, text="Click to mark:", font=("", 11, "bold")).pack(pady=10)
         
             for i in range(5):
                 btn = ttk.Button(
                     top, 
                     text=nombres[i].upper(), 
                     width=28,
                     bootstyle="secondary",
                     cursor="hand2"
                 )
                 btn.config(command=lambda i=i: toggle_boton(i))
                 btn.pack(pady=6)
                 botones_lista.append(btn)
         
             ttk.Button(
                 top, 
                 text="OK", 
                 command=top.destroy, 
                 bootstyle="primary",
                 cursor="hand2"
             ).pack(fill="x", pady=20)
         
             self.frame_contenedor.wait_window(top)
             n = [v.get() for v in vars_opciones]
    
             if n[3] == 1: 
                 self.function_input_advanced_vyazovkin_method(self.frame_contenedor) 
             elif n[4] == 1: 
                 self.function_input_vyazovkin_method(self.frame_contenedor)
         
             try:
                 self.isoTables = self.xtr.Isoconversion(d_a=self.d_a1)
                 self.ace = pnk.ActivationEnergy(self.Beta, self.T0, self.isoTables)   
            
                 if n[0] == 1:
                     self.ace.Fr()
                     self.nombres_aux.append("Friedman")
                     
                 if n[1] == 1:
                     self.ace.KAS()
                     self.nombres_aux.append("Kissinger-Akahira-Sunose")
                          
                 if n[2] == 1:
                     self.ace.OFW()
                     self.nombres_aux.append("Flynn-Wall-Ozawa")
                 
                 if n[3] == 1:
                     ventana_espera = ttk.Toplevel(self.frame_contenedor)
                     ventana_espera.title("Please wait")
                     ventana_espera.geometry("280x120")
                     ventana_espera.resizable(False, False)
                     ventana_espera.configure(padx=15, pady=15)
                     ventana_espera.attributes("-topmost", True)
                     
                     #ttk.Label(ventana_espera, text="Calculating Advance-Vyazovkin...", font=("", 10, "bold"), bootstyle="darkly").pack(pady=5)
                     ttk.Label(ventana_espera, text="Calculating Advance-Vyazovkin...", font=("", 10, "bold")).pack(pady=5)
                     
                     progreso = ttk.Progressbar(ventana_espera, mode="indeterminate", bootstyle="primary")
                     progreso.pack(fill="x", pady=5)
                     progreso.start(10)
                     
                     ventana_espera.update()
                     
                     try:
                         self.ace.aVy((self.x, self.y), var='time', p=self.p1)
                         self.nombres_aux.append("Advance-Vyazovkin")
                     finally:
                         ventana_espera.destroy()
                         
                 if n[4] == 1:
                     ventana_espera = ttk.Toplevel(self.frame_contenedor)
                     ventana_espera.title("Please wait")
                     ventana_espera.geometry("280x120")
                     ventana_espera.resizable(False, False)
                     ventana_espera.configure(padx=15, pady=15)
                     ventana_espera.attributes("-topmost", True)
                     
                     #ttk.Label(ventana_espera, text="Calculating Vyazovkin...", font=("", 10, "bold"), bootstyle="darkly").pack(pady=5)
                     ttk.Label(ventana_espera, text="Calculating Vyazovkin...", font=("", 10, "bold")).pack(pady=5)
                     progreso = ttk.Progressbar(ventana_espera, mode="indeterminate", bootstyle="info")
                     progreso.pack(fill="x", pady=5)
                     progreso.start(10)
                     
                     ventana_espera.update()
                     
                     try:
                         self.ace.Vy((self.x, self.y), method='senum-yang')
                         self.nombres_aux.append("Vyazovkin")
                     finally:
                         ventana_espera.destroy()
                         
                 self.fig = self.ace.Ea_plot()
                 self.draw_fig()
                 
             except Exception as e:
                 Messagebox.show_error(title="Error", message=f"Unexpected error: {e}")

    def iso_vy(self):
        """shows the graph of the vyazovkin method"""
        try:
           
            self.isoTables = self.xtr.Isoconversion(d_a=self.d_a1)
            self.ace = pnk.ActivationEnergy(self.Beta, self.T0, self.isoTables)
            self.ace.Vy((self.x, self.y),method='senum-yang')
            self.fig = self.ace.Ea_plot()
            self.draw_fig()
            
        except:
            messagebox.showerror("unexpected error")

    def iso_avy(self):
        """shows the graph of the avance vyazovkin method"""
        try:
           
            self.isoTables = self.xtr.Isoconversion(d_a=self.d_a1)
            self.ace = pnk.ActivationEnergy(self.Beta, self.T0, self.isoTables)
            self.ace.aVy((self.x, self.y), var='time', p=self.p1)
            self.fig = self.ace.Ea_plot()
            self.draw_fig()
            
        except:
            messagebox.showerror("unexpected error")

    def iso_fr(self):
        """shows the graph of the friedman method"""
        try:
        
            self.isoTables = self.xtr.Isoconversion(d_a=self.d_a1)
            self.ace = pnk.ActivationEnergy(self.Beta, self.T0, self.isoTables)
            self.ace.Fr() 
            self.fig = self.ace.Ea_plot()
            self.draw_fig()
            
        except Exception as e:
            messagebox.showerror("error",f"unexpected error {e}")

    def iso_kas(self):
        """shows the graph of the KAS method"""
        try:
           
            self.isoTables = self.xtr.Isoconversion(d_a=self.d_a1)
            self.ace = pnk.ActivationEnergy(self.Beta, self.T0, self.isoTables)
            self.ace.KAS()
            self.fig = self.ace.Ea_plot()
            self.draw_fig()

        except Exception as e:
            messagebox.showerror("error",f"unexpected error {e}")


    def iso_ofw(self):
        """shows the graph of the OFW method"""
        try:
           
            self.isoTables = self.xtr.Isoconversion(d_a=self.d_a1)
            self.ace = pnk.ActivationEnergy(self.Beta, self.T0, self.isoTables)
            self.ace.OFW()
            self.fig = self.ace.Ea_plot()
            self.draw_fig()
            
        except Exception as e:
            messagebox.showerror("error",f"unexpected error {e}")


    def chose_method_isoconversion(self):
        """ 
        The user chooses the isoconversion method they deem appropriate, after analyzing the previous method.
        """
        if self.one_step == []:
            messagebox.showinfo("open files", "open files, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input initial temperature, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input final temperature, please")
        elif self.conversion_aux==0:
            messagebox.showinfo("conversion", "execute conversion, please")
        elif self.d_a1==0:
            messagebox.showinfo("delta", "input value delta, please")
        else:
            
            ventana_isoconversion = ttk.Toplevel(self)
            ventana_isoconversion.title("Enter data")
            ventana_isoconversion.geometry("400x320")
            ventana_isoconversion.resizable(False, False)
            ventana_isoconversion.configure(padx=20, pady=20)
      
            #ttk.Label(ventana_isoconversion, text="Method:", font=("", 11, "bold"), bootstyle="darkly").pack(pady=5)
            ttk.Label(ventana_isoconversion, text="Method:", font=("", 11, "bold")).pack(pady=5)          
            cinco_metodos = self.nombres_aux
          
            if not cinco_metodos:
                cinco_metodos = ["No methods selected"]
          
            combo_methods = ttk.Combobox(ventana_isoconversion, values=cinco_metodos, state="readonly")
            combo_methods.set(cinco_metodos[0])
            combo_methods.pack(pady=10, fill="x")
          
            self.isoTables = self.xtr.Isoconversion(d_a=self.d_a1) 
            self.ace = pnk.ActivationEnergy(self.Beta, self.T0, self.isoTables)
         
            def guardar_y_cerrar():
                self.methods = combo_methods.get()
              
                # validation
                if self.methods == "No methods selected":
                    Messagebox.show_warning(title="Warning", message="You must choose a method in the previous process")
                    ventana_isoconversion.destroy()
                    return
    
                if self.methods == "Advance-Vyazovkin":

                    ventana_espera = ttk.Toplevel(self.frame_contenedor)
                    ventana_espera.title("Please wait")
                    ventana_espera.geometry("280x120")
                    ventana_espera.resizable(False, False)
                    ventana_espera.configure(padx=15, pady=15)
                    ventana_espera.attributes("-topmost", True)
                  
                    #ttk.Label(ventana_espera, text="Calculating...", font=("", 12, "bold"), bootstyle="darkly").pack(pady=10)
                    ttk.Label(ventana_espera, text="Calculating...", font=("", 12, "bold")).pack(pady=10)
                    progreso = ttk.Progressbar(ventana_espera, mode="indeterminate", bootstyle="primary")
                    progreso.pack(fill="x", pady=5)
                    progreso.start(10) # animation start
                  
                    ventana_espera.update() # force draw
                  
                    try:
                        self.method_used = self.ace.aVy((self.x, self.y), var='time', p=self.p1)
                    finally:
                        ventana_espera.destroy()
                      
                elif self.methods == "Vyazovkin":
                    ventana_espera = ttk.Toplevel(self.frame_contenedor)
                    ventana_espera.title("Please wait")
                    ventana_espera.geometry("280x120")
                    ventana_espera.resizable(False, False)
                    ventana_espera.configure(padx=15, pady=15)
                    ventana_espera.attributes("-topmost", True)
                  
                    #ttk.Label(ventana_espera, text="Calculating...", font=("", 12, "bold"), bootstyle="darkly").pack(pady=10)
                    ttk.Label(ventana_espera, text="Calculating...", font=("", 12, "bold")).pack(pady=10)
                    progreso = ttk.Progressbar(ventana_espera, mode="indeterminate", bootstyle="info")
                    progreso.pack(fill="x", pady=5)
                    progreso.start(10)
                  
                    ventana_espera.update()
                  
                    try:
                        self.method_used = self.ace.Vy((self.x, self.y), method='senum-yang')
                    finally:
                        ventana_espera.destroy()
                  
                elif self.methods == "Friedman":
                    self.method_used = self.ace.Fr() 
                
                elif self.methods == "Kissinger-Akahira-Sunose":
                    self.method_used = self.ace.KAS()
                 
                elif self.methods == "Flynn-Wall-Ozawa":
                    self.method_used = self.ace.OFW()
                
                else:
                    Messagebox.show_info(title="Info", message="You must choose a method in the previous process")
              
                ventana_isoconversion.destroy()
    
            # button ok
            button_algo = ttk.Button(
                ventana_isoconversion, 
                text="OK", 
                command=guardar_y_cerrar, 
                bootstyle="primary",
                cursor="hand2"
            )
            button_algo.pack(side=tk.BOTTOM, fill="x", pady=(20, 0))
            self.menu_start = 1
    
                

    def input_date_compensation(self):
        """ 
        This method inputs the data necessary for the Picnik compensation_effect method
        """
        
        if self.one_step == []:
            messagebox.showinfo("open files", "open files, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input initial temperature, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input final temperature, please")
        elif self.conversion_aux==0:
            messagebox.showinfo("conversion", "execute conversion, please")
        elif self.d_a1==0:
            messagebox.showinfo("delta", "input value delta, please")
        elif self.menu_start==None:
            messagebox.showinfo("isoconversion", "choose method isoconversion, please")
        
        else:
            fuente = ("", 12, "bold")
            
            # extend darkly
            ventana_compensation = ttk.Toplevel(self)
            ventana_compensation.title("Enter data")
            ventana_compensation.geometry("400x380")
            ventana_compensation.resizable(False, False)
            ventana_compensation.configure(padx=20, pady=20)
        
            # --- d_a ---
            opciones_beta = []
            for i in range(self.numero_de_archivos):
                texto = f"Beta {i} = {self.Beta[i]:.1f}"
                opciones_beta.append(texto)
            
            # use StringVar because the Spinbox now contains text (beta 0 = ...)
            valor_texto = tk.StringVar(value=opciones_beta[0])
            
            #ttk.Label(ventana_compensation, text="Select Beta:", font=("", 11, "bold"), bootstyle="darkly").pack(pady=5)
            ttk.Label(ventana_compensation, text="Select Beta:", font=("", 11, "bold")).pack(pady=5)
            
            # ttk spinbox
            spinbox_rango = ttk.Spinbox(
                ventana_compensation, 
                values=opciones_beta, 
                state="readonly", 
                textvariable=valor_texto,
                font=fuente,
                width=22
            )
            spinbox_rango.pack(pady=10, fill="x")
        
            # --- select model ---
            #ttk.Label(ventana_compensation, text="Select Model:", font=("", 11, "bold"), bootstyle="darkly").pack(pady=5)
            ttk.Label(ventana_compensation, text="Select Model:", font=("", 11, "bold")).pack(pady=5)
            options = ["r_Lin", "r_NL", "mse_NL"]
            
            # Combobox extends ttkbootstrap
            combo_options = ttk.Combobox(ventana_compensation, values=options, state="readonly")
            combo_options.set("r_Lin") # default value
            combo_options.pack(pady=10, fill="x")
        
            def actualizar_visibilidad(event=None):
                pass
            
            combo_options.bind("<<ComboboxSelected>>", actualizar_visibilidad)
            actualizar_visibilidad() # initial run
        
            # --- save data ---
            def guardar_y_cerrar():
                self.compensation_inicio = opciones_beta.index(valor_texto.get())
                self.compensation_error = combo_options.get()
                ventana_compensation.destroy()
        
            # --- button ok ---
            button_algo = ttk.Button(
                ventana_compensation, 
                text="OK", 
                command=guardar_y_cerrar,
                bootstyle="primary",
                cursor="hand2"
            )
            button_algo.pack(side=tk.BOTTOM, fill="x", pady=(20, 0))

    
    def ver_compensation_alpha(self):
        """
        visualize the compensation graph ln A vs alpha
        """
        
        if self.one_step == []:
            messagebox.showinfo("open files", "open files, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input initial temperature, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input final temperature, please")
        elif self.conversion_aux==0:
            messagebox.showinfo("conversion", "execute conversion, please")
        elif self.d_a1==0:
            messagebox.showinfo("delta", "input value delta, please")
        elif self.menu_start==None:
            messagebox.showinfo("isoconversion", "choose method isoconversion, please")
        elif self.compensation_inicio==None:
            messagebox.showinfo("compensation", "input compensation data , please")
            
        
        else:
        
            self.ace = pnk.ActivationEnergy(self.Beta, self.T0, self.isoTables)
            
            try:
        
                self.compensation = self.ace.compensation_effect(
                    self.compensation_inicio,
                    self.method_used[2],
                    self.method_used[3],
                    error_m=self.compensation_error
                )
        
                if self.compensation is None:
                    messagebox.showinfo("info","The compensation effect could not be calculated")
                    return
        
                self.fig = Figure(figsize=(7, 6), dpi=100)
                ax = self.fig.add_subplot(111)
        
                 
                ax.errorbar(
                    self.method_used[0],
                    self.compensation[0],
                    self.compensation[1],
                    fmt='o',
                    color='blue'
                )
        
                ax.set_xlabel(r'$\alpha$')
                ax.set_ylabel(r'$\ln(A_{\alpha})$')
                ax.set_title(r'$\ln(A)$ vs $\alpha$')
                ax.grid(True)
        
                self.fig.tight_layout()
                self.draw_fig()
                self.compensation_alphaE=1 
            except Exception as e:
                messagebox.showinfo("info",f"error in ver_compensation alpha {e}")
           
        #-----------------------------------------------------------------------------------#
    def ver_compensation_E(self):
        """
        visualize the compensation graph ln A vs E
        """
        if self.one_step == []:
            messagebox.showinfo("open files", "open files, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input initial temperature, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input final temperature, please")
        elif self.conversion_aux==0:
            messagebox.showinfo("conversion", "execute conversion, please")
        elif self.d_a1==0:
            messagebox.showinfo("delta", "input value delta, please")
        elif self.menu_start==None:
            messagebox.showinfo("isoconversion", "choose method isoconversion, please")
        elif self.compensation_inicio==None:
            messagebox.showinfo("compensation", "input compensation data , please")
        else:
        
            self.ace = pnk.ActivationEnergy(self.Beta, self.T0, self.isoTables)
            
            try:
        
                self.compensation = self.ace.compensation_effect(
                    self.compensation_inicio,
                    self.method_used[2],
                    self.method_used[3],
                    error_m=self.compensation_error
                )
        
                if self.compensation is None:
                    messagebox.showinfo("info","error calculate self.compensationensation effect")
                    return
        
                ln_A, errorlnA, a, errora, b, errorb, Afit, Efit, r_sq, mod = self.compensation
        
                self.fig = Figure(figsize=(7, 6), dpi=100)
                ax = self.fig.add_subplot(111)
        
                lnAfit = np.log(Afit)
        
                # points
                ax.scatter(
                    Efit,
                    lnAfit,
                    color='red',
                    s=60
                )
       
                # straight
                xfit = np.linspace(min(Efit), max(Efit), 100)
                yfit = a * xfit + b
        
                ax.plot(
                    xfit,
                    yfit,
                    color='black',
                    linewidth=2
                )
        
                # labels of models
                for i, m in enumerate(mod):
                    ax.text(
                        Efit[i],
                        lnAfit[i],
                        m.__name__,
                        fontsize=9
                    )
        
                ax.set_xlabel(r'$E$' )
                ax.set_ylabel(r'$\ln(A)$')
                ax.set_title(f"Compensation Effect ln A vs E              slope={a:.2f}  interception={b:.2f}")
                ax.grid(True) 
        
                self.fig.tight_layout()
                self.draw_fig()
                self.compensation_alphaE=1 
            except Exception as e:
                messagebox.showerror("error",f"compensation error {e}")
            
    
    def export_compensation_report(self):
        """ 
        View the compensation method data
        """
        
        if self.one_step == []:
            messagebox.showinfo("open files", "open files, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input initial temperature, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input final temperature, please")
        elif self.conversion_aux==0:
            messagebox.showinfo("conversion", "execute conversion, please")
        elif self.d_a1==0:
            messagebox.showinfo("delta", "input value delta, please")
        elif self.menu_start==None:
            messagebox.showinfo("isoconversion", "choose method isoconversion, please")
        elif self.compensation_inicio==None:
            messagebox.showinfo("compensation", "input compensation data , please")
        elif self.compensation_alphaE==None:
            messagebox.showinfo("compensation", "input compensation alpha or E data , please")   
        else:
        
            self.ace = pnk.ActivationEnergy(self.Beta, self.T0, self.isoTables)
            
            try:
        
                self.compensation = self.ace.compensation_effect(
                    self.compensation_inicio,
                    self.method_used[2],
                    self.method_used[3],
                    error_m=self.compensation_error
                )
        
                if self.compensation is None:
                    return
                
                rut = filedialog.asksaveasfilename(
                defaultextension=".txt",
                filetypes=[("files", "*.txt"), ("all files", "*.*")],
                title="select rute",
                initialfile="report_compensacion.txt"
                )
        
                # if the user cancels, exit the function
                if not rut:
                    return
        
                ln_A, errorlnA, a, errora, b, errorb, Afit, Efit, r_sq, mod = self.compensation
                alpha = self.method_used[0]
        
                # write to the selected file
                with open(rut, "w", encoding="utf-8") as f:
                    f.write("="*50 + "\n")
                    f.write("Compensation report\n")
                    f.write("="*50 + "\n\n")
        
                    f.write("Compensation parameters:\n\n")
                    f.write(f"slope (a) : {a}\n")
                    f.write(f"Error a : {errora}\n")
                    f.write(f"Interception (b): {b}\n")
                    f.write(f"Error b : {errorb}\n")
                    f.write("\n" + "-"*50 + "\n\n")
        
                    f.write("Accepted models:\n\n")
                    for i, model in enumerate(mod):
                        f.write(f"[{i+1}] {model.__name__}\n")
                        if i < len(Afit): f.write(f"  Afit = {Afit[i]}\n")
                        if i < len(Efit): f.write(f"  Efit = {Efit[i]}\n")
                        if i < len(r_sq): f.write(f"  R²   = {r_sq[i]}\n")
                        f.write("\n")
        
                    f.write(f"numbers of accepted models: {len(mod)}\n")
                    f.write("\n" + "-"*50 + "\n\n")
        
                    f.write("summery ln(Aα):\n\n")
                    f.write(f"alpha shape : {np.shape(alpha)}\n")
                    f.write(f"ln_A shape  : {np.shape(ln_A)}\n")
                    f.write(f"error shape : {np.shape(errorlnA)}\n")
                    f.write("\n" + "="*50 + "\n")
        
                
            except Exception as e:
                messagebox.showerror("error",f"compensation report error {e}")
    
            
    def ver_compensation_report(self):
        """
        save the compensation method data
        """
        if self.one_step == []:
            messagebox.showinfo("open files", "open files, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input initial temperature, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input final temperature, please")
        elif self.conversion_aux==0:
            messagebox.showinfo("conversion", "execute conversion, please")
        elif self.d_a1==0:
            messagebox.showinfo("delta", "input value delta, please")
        elif self.menu_start==None:
            messagebox.showinfo("isoconversion", "choose method isoconversion, please")
        elif self.compensation_inicio==None:
            messagebox.showinfo("comoensation", "input compensation data , please")   
        elif self.compensation_alphaE==None:
            messagebox.showinfo("comoensation", "input compensation alpha or E data , please")   
            
        else:
        
            self.ace = pnk.ActivationEnergy(self.Beta, self.T0, self.isoTables)
        
            try:
                # calculate the effect of the compensation
                self.compensation = self.ace.compensation_effect(
                    self.compensation_inicio,
                    self.method_used[2],
                    self.method_used[3],
                    error_m=self.compensation_error
                )
        
                if self.compensation is None:
                    return
                
                ln_A, errorlnA, a, errora, b, errorb, Afit, Efit, r_sq, mod = self.compensation
                alpha = self.method_used[0]
        
                rep_text = ""
                rep_text += "Summary Compensation Report\n"
                rep_text += "Compensation parameters:\n"
                rep_text += f"slope (a) : {a}\n"
                rep_text += f"Error a : {errora}\n"
                rep_text += f"Interception (b): {b}\n"
                rep_text += f"Error b : {errorb}\n"
                rep_text += "\n"
        
                rep_text += "Accepted models:\n\n"
                for i, model in enumerate(mod):
                    rep_text += f"[{i+1}] {model.__name__}\n"
                    if i < len(Afit): rep_text += f"  Afit = {Afit[i]}\n"
                    if i < len(Efit): rep_text += f"  Efit = {Efit[i]}\n"
                    if i < len(r_sq): rep_text += f"  R²   = {r_sq[i]}\n"
                    rep_text += "\n"
        
                rep_text += f"numbers of accepted models: {len(mod)}\n"
                rep_text += "\n" + "-"*50 + "\n\n"
        
                rep_text += "summery ln(Aα):\n\n"
                rep_text += f"alpha shape : {np.shape(alpha)}\n"
                rep_text += f"ln_A shape  : {np.shape(ln_A)}\n"
                rep_text += f"error shape : {np.shape(errorlnA)}\n"
                rep_text += "\n" + "="*50 + "\n"
        
                # text view
                self.fig = Figure(figsize=(7, 8), dpi=100)
                ax = self.fig.add_subplot(111)
                
                # hide everything except the text
                ax.axis('off')
        
                # text position
                ax.text(
                    0.01, 0.99, 
                    rep_text, 
                    fontsize=8, 
                    family='monospace',
                    verticalalignment='top',
                    horizontalalignment='left',
                    transform=ax.transAxes
                )
        
                self.fig.tight_layout()
                
    
                self.draw_fig()
                
            except Exception as e:
                messagebox.showerror("error",f"compensation report error {e}")

        
         

    def ver_recontruction(self):
        """ 
        This method is called picnik reconstruction method
        """
        
        if self.one_step == []:
            messagebox.showinfo("open files", "open files, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input initial temperature, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input final temperature, please")
        elif self.conversion_aux==0:
            messagebox.showinfo("conversion", "execute conversion, please")
        elif self.d_a1==0:
            messagebox.showinfo("delta", "input value delta, please")
        elif self.menu_start==None:
            messagebox.showinfo("isoconversion", "choose method isoconversion, please")
        elif self.compensation_inicio==None:
            messagebox.showinfo("comoensation", "input compensation data , please")   
        elif self.compensation_alphaE==None:
            messagebox.showinfo("comoensation", "input compensation alpha or E data , please")   
        else:
        
            try:
            # clean frame
                for widget in self.frame_grafico.winfo_children():
                    widget.destroy()
        
                self.fig, self.g_a = self.ace.reconstruction(
                    self.method_used[2],
                    np.exp(self.compensation[0]),
                    self.Beta[self.compensation_inicio]
                    
                )
        
                self.draw_fig()
    
            except Exception as e:
                messagebox.showerror("error",f"reconstruction error {e}")

           

    
    def export_data_ea(self):
        """
        Activation energy data is exported
        """
        if self.one_step == []:
            messagebox.showinfo("open files", "open files, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input initial temperature, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input final temperature, please")
        elif self.conversion_aux==0:
            messagebox.showinfo("conversion", "execute conversion, please")
        elif self.d_a1==0:
            messagebox.showinfo("delta", "input value delta, please")
        elif self.menu_start==None:
            messagebox.showinfo("isoconversion", "choose method isoconversion, please")
        
        else:
               
            try:
                if self.ace.export_Ea(): 
                    messagebox.showinfo("correct", "data exported successfully")
                else: 
                    print("save cancel.")
            except Exception as e:
                messagebox.showerror("error",f"export files error {e}")


           

    def save_kinetic_triplet(self):
        """
        This method exports the kinetic data: activation energy, 
        natural logarithm of the pre-exponential factor, and reaction model.
        """
    
        if self.one_step == []:
            messagebox.showinfo("open files", "open files, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input initial temperature, please")
        elif self.fix1_conversion==[]:
            messagebox.showinfo("temperature", "input final temperature, please")
        elif self.conversion_aux==0:
            messagebox.showinfo("conversion", "execute conversion, please")
        elif self.d_a1==0:
            messagebox.showinfo("delta", "input value delta, please")
        elif self.menu_start==None:
            messagebox.showinfo("isoconversion", "choose method isoconversion, please")
        elif self.compensation_inicio==None:
            messagebox.showinfo("comoensation", "input compensation data , please")
        elif self.compensation_alphaE==None:
            messagebox.showinfo("comoensation", "input compensation alpha or E data , please")   
        else:
    
            try:
                
                "Kinetic triplet"
                if self.ace.export_kinetic_triplet(self.method_used[0][1::], self.method_used[2][1::], self.compensation[0][1::], self.g_a, name="kinetic_triplet.csv" ):
                    messagebox.showinfo("correct","data exported successfull")
                else:
                    print("save cancel")
            except Exception as e:
                messagebox.showerror("error",f"export files error {e}")


   
    def save_image_picnik(self): 
        """
        Save the canvas images to a user-selected folder on your computer.
        """
        if self.fig is None:
            messagebox.showwarning("save image", "No image to save.")
            return

        file = filedialog.asksaveasfilename(
            #defaultextension=".png",
            filetypes=[("SVG files", "*.svg"),
                    ("PNG files", "*.png")
                    ]
        )
        if file:
            self.fig.savefig(file, dpi=300, bbox_inches='tight')
            messagebox.showinfo("save image", f"Chart saved in:\n{file}")
            

    def about_picnik(self):
        """
        Link to picnik project information
        """
        messagebox.showinfo("about", "picnik aplicacion\nVersion 1.0\n https://doi.org/10.1016/j.cpc.2022.108416")
    
    
        
    def function_tutorial(self):
        """
        Open a PDF with a tutorial on how to use the application.
        """
        if hasattr(sys, '_MEIPASS'):
            # if it's already compiled with PyInstaller, use the temporary folder
            base_path = sys._MEIPASS
        else:
            # for IDE
            base_path = os.path.dirname(os.path.abspath(__file__))
            
        rut_orig = os.path.join(base_path, "tutorial.pdf")
                 
        if sys.platform.startswith('darwin'):  # macOS
            subprocess.Popen(['open', rut_orig])
            
        elif os.name == 'nt':  # Windows
            os.startfile(rut_orig)
            
        elif os.name == 'posix':  # Linux
            try:
                if not os.path.exists(rut_orig):
                    print(f"Error: no file in: {rut_orig}")
                    return
                
                #gets the actual path of documents dynamically based on the language
                import subprocess
                try:
                    resultado = subprocess.run(["xdg-user-dir", "DOCUMENTS"], capture_output=True, text=True, check=True)
                    carpeta_usuario = resultado.stdout.strip()
                except Exception:
                    # Alternative if xdg-user-dir fails
                    carpeta_usuario = os.path.expanduser("~/Documents")
                
                os.makedirs(carpeta_usuario, exist_ok=True)
                rut_dest = os.path.join(carpeta_usuario, "Manual_Tutorial.pdf")
                
                shutil.copy2(rut_orig, rut_dest)
                
                enviroment_clean = dict(os.environ)
                if 'LD_LIBRARY_PATH_ORIG' in enviroment_clean:
                    enviroment_clean['LD_LIBRARY_PATH'] = enviroment_clean.pop('LD_LIBRARY_PATH_ORIG')
                elif 'LD_LIBRARY_PATH' in enviroment_clean:
                    enviroment_clean.pop('LD_LIBRARY_PATH')
                    
                subprocess.Popen(["xdg-open", rut_dest], env=enviroment_clean)
                print(f"open PDF from: {rut_dest}")
            
            except Exception as e:
                messagebox.showerror("error",f"open files in linux {e}")
                
 


if __name__ == "__main__":
    app = Aplicacion()
    app.mainloop()
